import { Geist, Geist_Mono, Montserrat, Onest } from "next/font/google";
import "../styles/globals.css";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${onest.variable} ${montserrat.variable} antialiased selection:bg-[#FFC017]`}
      >
        {children}
      </body>
    </html>
  );
}
